# version: '3'

# Networking: https://www.architect.io/blog/2023-03-23/manage-networking-with-docker-compose/

services:
  
  qsign:
    image: xzhouqd/qsign:core-1.1.9
    expose:
      - 8080
    environment:
      BASE_PATH: "/srv/qsign/qsign/txlib/8.9.63"
    restart: always
    networks:
      - cq
    container_name: cq-sign

  cqhttp:
    build:
      context: ./docker/cqhttp
      dockerfile: Dockerfile
    container_name: cq-http
    networks:
      - backend
      - cq
    restart: always
    depends_on:
      - qsign
      - server

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    expose:
      - 3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: bilibili_database
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: server
      MYSQL_PASSWORD: y2A@kw9&
    container_name: bilibili-mysql
    restart: always
    networks:
      - backend
    command: --default-authentication-plugin=caching_sha2_password

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    expose:
      - 6379
    networks:
      - backend
    container_name: bilibili-redis
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bilibili-server
    networks:
      - backend
      - cq
    expose:
      - 8998
    restart: always
    depends_on:
      - redis
      - mysql

networks:
  backend:
  cq:
