# version: '3'

# Networking: https://www.architect.io/blog/2023-03-23/manage-networking-with-docker-compose/

services:
  
  mysql:
    image: bilibilitools-mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: bilibili_database
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: server
      MYSQL_PASSWORD: y2A@kw9&
    container_name: bilibili-mysql
    restart: always
    networks:
      - backend
    command: --default-authentication-plugin=caching_sha2_password

  redis:
    image: bilibilitools-redis:latest
    expose:
      - 6379
    networks:
      - backend
    container_name: bilibili-redis
    restart: always

  server:
    image: bilibilitools-server:latest
    container_name: bilibili-server
    networks:
      - backend
    expose:
      - 8998
    restart: always
    depends_on:
      - redis
      - mysql

  lagrange:
    image: bilibilitools-lagrange:latest
    container_name: bilibili-lagrange
    networks:
      - backend
    restart: always
    depends_on:
      - server

networks:
  backend:
