/**
 *
 *  LiveNotify.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "LiveNotify.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::bilibili_database;

const std::string LiveNotify::Cols::_id = "id";
const std::string LiveNotify::Cols::_notify_target = "notify_target";
const std::string LiveNotify::Cols::_target_type = "target_type";
const std::string LiveNotify::Cols::_subscribe_target = "subscribe_target";
const std::string LiveNotify::primaryKeyName = "id";
const bool LiveNotify::hasPrimaryKey = true;
const std::string LiveNotify::tableName = "live_notify";

const std::vector<typename LiveNotify::MetaData> LiveNotify::metaData_={
{"id","uint32_t","int unsigned",4,1,1,1},
{"notify_target","std::string","varchar(20)",20,0,0,1},
{"target_type","std::string","enum('PRIVATE','GROUP')",0,0,0,1},
{"subscribe_target","std::string","varchar(20)",20,0,0,1}
};
const std::string &LiveNotify::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
LiveNotify::LiveNotify(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<uint32_t>(r["id"].as<uint32_t>());
        }
        if(!r["notify_target"].isNull())
        {
            notifyTarget_=std::make_shared<std::string>(r["notify_target"].as<std::string>());
        }
        if(!r["target_type"].isNull())
        {
            targetType_=std::make_shared<std::string>(r["target_type"].as<std::string>());
        }
        if(!r["subscribe_target"].isNull())
        {
            subscribeTarget_=std::make_shared<std::string>(r["subscribe_target"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            notifyTarget_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            targetType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            subscribeTarget_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

LiveNotify::LiveNotify(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            notifyTarget_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            subscribeTarget_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

LiveNotify::LiveNotify(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint32_t>((uint32_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("notify_target"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["notify_target"].isNull())
        {
            notifyTarget_=std::make_shared<std::string>(pJson["notify_target"].asString());
        }
    }
    if(pJson.isMember("target_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["target_type"].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson["target_type"].asString());
        }
    }
    if(pJson.isMember("subscribe_target"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["subscribe_target"].isNull())
        {
            subscribeTarget_=std::make_shared<std::string>(pJson["subscribe_target"].asString());
        }
    }
}

void LiveNotify::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            notifyTarget_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            subscribeTarget_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void LiveNotify::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint32_t>((uint32_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("notify_target"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["notify_target"].isNull())
        {
            notifyTarget_=std::make_shared<std::string>(pJson["notify_target"].asString());
        }
    }
    if(pJson.isMember("target_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["target_type"].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson["target_type"].asString());
        }
    }
    if(pJson.isMember("subscribe_target"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["subscribe_target"].isNull())
        {
            subscribeTarget_=std::make_shared<std::string>(pJson["subscribe_target"].asString());
        }
    }
}

const uint32_t &LiveNotify::getValueOfId() const noexcept
{
    static const uint32_t defaultValue = uint32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &LiveNotify::getId() const noexcept
{
    return id_;
}
void LiveNotify::setId(const uint32_t &pId) noexcept
{
    id_ = std::make_shared<uint32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename LiveNotify::PrimaryKeyType & LiveNotify::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &LiveNotify::getValueOfNotifyTarget() const noexcept
{
    static const std::string defaultValue = std::string();
    if(notifyTarget_)
        return *notifyTarget_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LiveNotify::getNotifyTarget() const noexcept
{
    return notifyTarget_;
}
void LiveNotify::setNotifyTarget(const std::string &pNotifyTarget) noexcept
{
    notifyTarget_ = std::make_shared<std::string>(pNotifyTarget);
    dirtyFlag_[1] = true;
}
void LiveNotify::setNotifyTarget(std::string &&pNotifyTarget) noexcept
{
    notifyTarget_ = std::make_shared<std::string>(std::move(pNotifyTarget));
    dirtyFlag_[1] = true;
}

const std::string &LiveNotify::getValueOfTargetType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(targetType_)
        return *targetType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LiveNotify::getTargetType() const noexcept
{
    return targetType_;
}
void LiveNotify::setTargetType(const std::string &pTargetType) noexcept
{
    targetType_ = std::make_shared<std::string>(pTargetType);
    dirtyFlag_[2] = true;
}
void LiveNotify::setTargetType(std::string &&pTargetType) noexcept
{
    targetType_ = std::make_shared<std::string>(std::move(pTargetType));
    dirtyFlag_[2] = true;
}

const std::string &LiveNotify::getValueOfSubscribeTarget() const noexcept
{
    static const std::string defaultValue = std::string();
    if(subscribeTarget_)
        return *subscribeTarget_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LiveNotify::getSubscribeTarget() const noexcept
{
    return subscribeTarget_;
}
void LiveNotify::setSubscribeTarget(const std::string &pSubscribeTarget) noexcept
{
    subscribeTarget_ = std::make_shared<std::string>(pSubscribeTarget);
    dirtyFlag_[3] = true;
}
void LiveNotify::setSubscribeTarget(std::string &&pSubscribeTarget) noexcept
{
    subscribeTarget_ = std::make_shared<std::string>(std::move(pSubscribeTarget));
    dirtyFlag_[3] = true;
}

void LiveNotify::updateId(const uint64_t id)
{
    id_ = std::make_shared<uint32_t>(static_cast<uint32_t>(id));
}

const std::vector<std::string> &LiveNotify::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "notify_target",
        "target_type",
        "subscribe_target"
    };
    return inCols;
}

void LiveNotify::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNotifyTarget())
        {
            binder << getValueOfNotifyTarget();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTargetType())
        {
            binder << getValueOfTargetType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSubscribeTarget())
        {
            binder << getValueOfSubscribeTarget();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> LiveNotify::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void LiveNotify::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNotifyTarget())
        {
            binder << getValueOfNotifyTarget();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTargetType())
        {
            binder << getValueOfTargetType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSubscribeTarget())
        {
            binder << getValueOfSubscribeTarget();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value LiveNotify::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNotifyTarget())
    {
        ret["notify_target"]=getValueOfNotifyTarget();
    }
    else
    {
        ret["notify_target"]=Json::Value();
    }
    if(getTargetType())
    {
        ret["target_type"]=getValueOfTargetType();
    }
    else
    {
        ret["target_type"]=Json::Value();
    }
    if(getSubscribeTarget())
    {
        ret["subscribe_target"]=getValueOfSubscribeTarget();
    }
    else
    {
        ret["subscribe_target"]=Json::Value();
    }
    return ret;
}

Json::Value LiveNotify::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNotifyTarget())
            {
                ret[pMasqueradingVector[1]]=getValueOfNotifyTarget();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTargetType())
            {
                ret[pMasqueradingVector[2]]=getValueOfTargetType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSubscribeTarget())
            {
                ret[pMasqueradingVector[3]]=getValueOfSubscribeTarget();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNotifyTarget())
    {
        ret["notify_target"]=getValueOfNotifyTarget();
    }
    else
    {
        ret["notify_target"]=Json::Value();
    }
    if(getTargetType())
    {
        ret["target_type"]=getValueOfTargetType();
    }
    else
    {
        ret["target_type"]=Json::Value();
    }
    if(getSubscribeTarget())
    {
        ret["subscribe_target"]=getValueOfSubscribeTarget();
    }
    else
    {
        ret["subscribe_target"]=Json::Value();
    }
    return ret;
}

bool LiveNotify::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("notify_target"))
    {
        if(!validJsonOfField(1, "notify_target", pJson["notify_target"], err, true))
            return false;
    }
    else
    {
        err="The notify_target column cannot be null";
        return false;
    }
    if(pJson.isMember("target_type"))
    {
        if(!validJsonOfField(2, "target_type", pJson["target_type"], err, true))
            return false;
    }
    if(pJson.isMember("subscribe_target"))
    {
        if(!validJsonOfField(3, "subscribe_target", pJson["subscribe_target"], err, true))
            return false;
    }
    else
    {
        err="The subscribe_target column cannot be null";
        return false;
    }
    return true;
}
bool LiveNotify::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LiveNotify::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("notify_target"))
    {
        if(!validJsonOfField(1, "notify_target", pJson["notify_target"], err, false))
            return false;
    }
    if(pJson.isMember("target_type"))
    {
        if(!validJsonOfField(2, "target_type", pJson["target_type"], err, false))
            return false;
    }
    if(pJson.isMember("subscribe_target"))
    {
        if(!validJsonOfField(3, "subscribe_target", pJson["subscribe_target"], err, false))
            return false;
    }
    return true;
}
bool LiveNotify::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LiveNotify::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
